apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: httpbin
  namespace: default
  labels:
    app: ingress-nginx
    version: 0.1
spec:
  releaseName: httpbin
  chart:
    spec:
      chart: ./charts/httpbin
      sourceRef:
        kind: GitRepository
        name: httpbin
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
    namespace: istio-system
  - name: ingress-nginx
    namespace: default
  interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/service-upstream: "true"
        nginx.ingress.kubernetes.io/upstream-vhost: httpbin.default.svc.cluster.local
      hosts:
      - host: httpbin.local
        paths: [ / ]