apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: httpbin
  namespace: default
spec:
  releaseName: httpbin
  chart:
    spec:
      chart: ./charts/httpbin
      sourceRef:
        kind: GitRepository
        name: httpbin
        namespace: flux-system
  dependsOn:
    # - name: istio-discovery
    #   namespace: istio-system
    - name: ingress-nginx
      namespace: default
  interval: 5m
  values:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        nginx.ingress.kubernetes.io/service-upstream: "true"
        nginx.ingress.kubernetes.io/upstream-vhost: httpbin.default.svc.cluster.local
        traffic.sidecar.istio.io/excludeOutboundIPRanges: "10.96.0.1/32"
      hosts:
        - host: httpbin.local
          paths: [/]
