apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: istio-system
spec:
  releaseName: grafana
  chart:
    spec:
      chart: ./charts/grafana
      sourceRef:
        kind: GitRepository
        name: grafana
        namespace: flux-system
  interval: 5m
  values:
    env:
      JAEGER_AGENT_PORT: "5775"