apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
spec:
  releaseName: kiali
  chart:
    spec:
      chart: ./kiali-server
      sourceRef:
        kind: GitRepository
        name: kiali
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  interval: 5m
  values:
    auth:
      strategy: "anonymous"
    deployment:
      image_version: v1.35.0
      version_label: v1.35.0
      pod_annotations:
        sidecar.istio.io/inject: "false"
    external_services:
      grafana:
        url: http://grafana.istio-system
      prometheus:
        url: http://prometheus-server.istio-system
      custom_dashboards:
        enabled: true