apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
spec:
  releaseName: kiali
  chart:
    spec:
      chart: ./kiali-server
      sourceRef:
        kind: GitRepository
        name: kiali
        namespace: flux-system
  interval: 5m
  values:
    auth:
      strategy: "anonymous"