apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kiali
  namespace: istio-system
spec:
  releaseName: kiali
  chart:
    spec:
      chart: ./kiali-server
      sourceRef:
        kind: GitRepository
        name: kiali
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  - name: ingress-nginx
    namespace: default
  - name: jaeger
  - name: grafana
  - name: prometheus
  interval: 5m
  values:
    auth:
      strategy: "anonymous"
    deployment:
      image_version: v1.35.0
      version_label: v1.35.0
      pod_annotations:
        sidecar.istio.io/inject: "false"
      custom_dashboards:
        excludes:
        - ""
        includes:
        - '*'
      ingress_enabled: false
      secret_name: kiali
    istio_namespace: istio-system
    server:
      port: 20001
      metrics_enabled: true
      metrics_port: 80
      web_root: /kiali
    external_services:
      tracing:
        auth:
          ca_file: ''
          insecure_skip_verify: true
          password: ''
          token: ''
          type: none
          use_kiali_token: false
          username: ''
        enabled: true
        in_cluster_url: "http://jaeger-query.istio-system"
        namespace_selector: true
        # url: 'http://localhost/jaeger'
        whitelist_istio_system:
        - jaeger-query
        - istio-ingressgateway
      grafana:
        auth:
          ca_file: ''
          component_status:
            app_label: grafana
            is_core: false
          insecure_skip_verify: false
          password: ''
          token: ''
          type: none
          use_kiali_token: false
          username: ''
        dashboards:
        - name: Istio Service Dashboard
          variables:
            namespace: var-namespace
            service: var-service
        - name: Istio Workload Dashboard
          variables:
            namespace: var-namespace
            workload: var-workload
        enabled: true
        in_cluster_url: http://grafana.istio-system
        url: "http://grafana.local"
      prometheus:
        url: http://prometheus-server.istio-system
      custom_dashboards:
        enabled: true