apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: istio-system
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: ./charts/prometheus
      sourceRef:
        kind: GitRepository
        name: prometheus
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  # - name: jaeger
  interval: 5m
  values:
    serviceAccounts:
      alertmanager:
        create: false
      nodeExporter:
        create: false
      pushgateway:
        create: false
      server:
        create: true
    server:
      service:
          servicePort: 9090
      podAnnotations:
        sidecar.istio.io/inject: "false"
      global:
        evaluation_interval: 1m
        scrape_interval: 15s
        scrape_timeout: 10s
      env:
      - name: JAEGER_AGENT_PORT
        value: "5775"
    alertmanager:
      enabled: false
    kubeStateMetrics:
      enabled: false
    nodeExporter:
      enabled: false
    pushgateway:
      enabled: false