apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: istio-system
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: ./charts/prometheus
      sourceRef:
        kind: GitRepository
        name: prometheus
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  interval: 5m
  values:
    server:
      podAnnotations:
        sidecar.istio.io/inject: "false"
      env:
      - name: JAEGER_AGENT_PORT
        value: "5775"
    alertmanager:
      podAnnotations:
        sidecar.istio.io/inject: "false"
    kubeStateMetrics:
      podAnnotations:
        sidecar.istio.io/inject: "false"
    nodeExporter:
      podAnnotations:
        sidecar.istio.io/inject: "false"
    pushgateway:
      podAnnotations:
        sidecar.istio.io/inject: "false"