apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: istio-system
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: ./charts/prometheus
      sourceRef:
        kind: GitRepository
        name: prometheus
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  interval: 5m
  values:
    server:
      podAnnotations:
        # Exclude outbound traffic to kubernetes master from redirection.
        traffic.sidecar.istio.io/excludeOutboundIPRanges: "10.96.0.1/32"
      env:
      - name: JAEGER_AGENT_PORT
        value: "5775"