apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prometheus
  namespace: istio-system
spec:
  releaseName: prometheus
  chart:
    spec:
      chart: ./charts/prometheus
      sourceRef:
        kind: GitRepository
        name: prometheus
        namespace: flux-system
  interval: 5m
  values:
    env:
    - name: JAEGER_AGENT_PORT
      value: "5775"