apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: istio-discovery
spec:
  releaseName: istio-discovery
  chart:
    spec:
      chart: ./manifests/charts/istio-control/istio-discovery
      sourceRef:
        kind: GitRepository
        name: istio
        namespace: flux-system
  dependsOn:
  - name: istio-base
  interval: 5m
  values:
    meshConfig:
      enableTracing: true
    pilot:
      traceSampling: 100
      autoscaleEnabled: true
      autoscaleMin: 1
      autoscaleMax: 3
    sidecarInjectorWebhook:
      enableNamespacesByDefault: true
    telemetry:
      enabled: true
      v2:
        prometheus:
          enabled: true
    global:
      hub: docker.io/istio
      tag: "1.10.3"
      proxy:
        tracer: "zipkin"
      tracer:
        zipkin:
          address: "zipkin.istio-system:9411"