apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-kafka
  namespace: istio-system
spec:
  releaseName: jaeger-kafka
  chart:
    spec:
      chart: ./charts/jaeger
      sourceRef:
        kind: GitRepository
        name: jaeger
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  interval: 5m
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: false
      kafka: true
    agent:
      enabled: false
    query:
      enabled: false
    collector:
      enabled: false
    ingester:
      enabled: false
    kafka:
      podAnnotations:
        sidecar.istio.io/inject: "false"
      replicaCount: 1
      autoCreateTopicsEnable: true
      zookeeper:
        replicaCount: 1
        serviceAccount:
          create: true
