apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-query
  namespace: istio-system
spec:
  releaseName: jaeger-query
  chart:
    spec:
      chart: ./charts/jaeger
      sourceRef:
        kind: GitRepository
        name: jaeger
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  interval: 5m
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: false
      kafka: false
    storage:
      type: elasticsearch
      elasticsearch:
        scheme: http
        host: elasticsearch-master
        port: 9200
        user: elastic
        usePassword: true
        password: changeme
        nodesWanOnly: false
        # extraEnv: []
        # cmdlineParams: {}
    agent:
      enabled: false
    collector:
      enabled: false
    ingester:
      enabled: false
    query:
      podAnnotations:
        sidecar.istio.io/inject: "false"
      ingress:
        enabled: true
        hosts:
        - jaeger.local
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
      # extraEnv: