apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: istio-system
spec:
  releaseName: jaeger
  chart:
    spec:
      chart: ./charts/jaeger
      sourceRef:
        kind: GitRepository
        name: jaeger
        namespace: flux-system
  dependsOn:
  # - name: ingress-nginx
  #   namespace: default
  - name: istio-discovery
  interval: 5m
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: true
      kafka: true
    storage:
      # allowed values (cassandra, elasticsearch)
      # type: cassandra
      # type: elasticsearch
      type: kafka
    # cassandra:
    #   podAnnotations:
    #     sidecar.istio.io/inject: "false"
    #   config:
    #     cluster_size: 1
    elasticsearch:
      podAnnotations:
        sidecar.istio.io/inject: "false"
      image: "docker.elastic.co/elasticsearch/elasticsearch"
      imageTag: "7.15.0"
      replicas: 1
      minimumMasterNodes: 1
      clusterHealthCheckParams: 'wait_for_status=yellow&timeout=1s'
    schema:
      podAnnotations:
        sidecar.istio.io/inject: "false"
    agent:
      podAnnotations:
        sidecar.istio.io/inject: "false"
    collector:
      podAnnotations:
        sidecar.istio.io/inject: "false"
      service:
        zipkin:
          port: 9411
      # Used to create an Ingress record.
      ingress:
        enabled: false
        hosts:
        - jaeger-collector.local
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
    query:
      podAnnotations:
        sidecar.istio.io/inject: "false"
      # Used to create an Ingress record.
      ingress:
        enabled: true
        hosts:
        - jaeger.local
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"
    ingester:
      enabled: false