apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: istio-system
spec:
  releaseName: jaeger
  chart:
    spec:
      chart: ./charts/jaeger
      sourceRef:
        kind: GitRepository
        name: jaeger
        namespace: flux-system
  dependsOn:
  - name: istio-discovery  
  interval: 5m
  values:
    provisionDataStore:
      cassandra: true
      elasticsearch: false
      kafka: false
    storage:
      # allowed values (cassandra, elasticsearch)
      type: cassandra
    cassandra:
      podAnnotations:
        sidecar.istio.io/inject: "false"
      config:
        cluster_size: 1
    schema:
      podAnnotations:
        sidecar.istio.io/inject: "false"
    agent:
      podAnnotations:
        sidecar.istio.io/inject: "false"
    collector:
      podAnnotations:
        sidecar.istio.io/inject: "false"
    query:
      podAnnotations:
        sidecar.istio.io/inject: "false"