apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger-agent
  namespace: istio-system
spec:
  releaseName: jaeger-agent
  chart:
    spec:
      chart: ./charts/jaeger
      sourceRef:
        kind: GitRepository
        name: jaeger
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  interval: 5m
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: false
      kafka: false
    storage:
      type: elasticsearch
    agent:
      podAnnotations:
        sidecar.istio.io/inject: "false"
    collector:
      enabled: false
    ingester:
      enabled: false
    query:
      enabled: false