apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jaeger
  namespace: istio-system
spec:
  releaseName: jaeger-collector
  chart:
    spec:
      chart: ./charts/jaeger
      sourceRef:
        kind: GitRepository
        name: jaeger
        namespace: flux-system
  dependsOn:
  - name: istio-discovery
  interval: 5m
  values:
    provisionDataStore:
      cassandra: false
      elasticsearch: false
      kafka: false
    storage:
      # allowed values (cassandra, elasticsearch)
      # type: cassandra
      # type: elasticsearch
      type: kafka
      kafka:
        brokers:
          - jaeger-kafka-headless:9092
        topic: jaeger_v1_test
        authentication: none
        # extraEnv: []
    agent:
      enabled: false
    query:
      enabled: false
    ingester:
      enabled: false
    collector:
      podAnnotations:
        sidecar.istio.io/inject: "false"
      service:
        zipkin:
          port: 9411
      ingress:
        enabled: false
        hosts:
        - jaeger-collector.local
        annotations:
          kubernetes.io/ingress.class: nginx
          kubernetes.io/tls-acme: "true"